### ISSUE TITLE
`@sanity/client` from file

### ISSUE THREAD

**Issue by brian-musarafu** [sanity-io/client#138]
While trying to resolve module `@sanity/client` from file `C:\Users\musar\Downloads\hit-400-app\sanity.js`, the package `C:\Users\musar\Downloads\hit-400-app\node_modules\@sanity\client\package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`C:\Users\musar\Downloads\hit-400-app\node_modules\@sanity\client\dist\index.browser.cjs`. Indeed, none of these files exist:

**Comment by stipsan** [comment]
I think there's something wrong with how your project installs `node_modules`. As you can see here, the files are published: 
- https://unpkg.com/browse/@sanity/client@5.2.2/dist/index.browser.cjs
- https://unpkg.com/browse/@sanity/client@5.2.2/dist/
