### ISSUE TITLE
Deprecation warning shown even if I don't use default export

### ISSUE THREAD

**Issue by pascalwengerter** [sanity-io/client#158]
When running `@sanity/client` (issue was present in v5.2.x, I've updated to v5.3.0 now and still see it) in my Nuxt3 project, I always see

![Screenshot 2023-03-14 at 12 28 36](https://user-images.githubusercontent.com/16822008/224987864-d2ea7719-fd21-45a1-8c36-7b5d49f6bce9.png)

even though I only use named exports from `@sanity/client` in my project.

**Comment by stipsan** [comment]
Hi, then there might be another library that's using it, perhaps in your `node_modules`?

As you can see we're only printing this message if something is calling the default export: https://github.com/sanity-io/client/blob/da0d23c16f18ea437b1924a09e1eaf20644c2882/src/index.ts#L26

In other words, this is not enough for the deprecation warning to print:
```
import sanityClient from '@sanity/client'
```
Somewhere in your project _something_ must be calling it:
```
sanityClient()
```

You can quickly find out what's doing it by editing `./node_modules/@sanity/client/dist/${index.js,index.cjs,index.browser.js,index.browser.cjs}` and you'll find `function deprecatedCreateClient` at the very bottom:
```diff
function deprecatedCreateClient(config) {
- printNoDefaultExport();
+ throw new Error('Found the culprit!')
 return new SanityClient(httpRequest, config);
}
```

**Comment by pascalwengerter** [comment]
This has been resolved in one of the more recent dependency bumps in my project, thanks for the throughout answer nonetheless!
