### ISSUE TITLE
Adding Sanity client breaks new Hydrogen storefront

### ISSUE THREAD

**Issue by LukasMurdock** [sanity-io/client#177]
**Steps to reproduce**

1. Create a new Hydrogen app: [https://shopify.dev/docs/custom-storefronts/hydrogen/getting-started/quickstart](https://shopify.dev/docs/custom-storefronts/hydrogen/getting-started/quickstart)
2. Choose `hello world` template
3. Choose `TypeScript`
4. Install dependencies
5. Install Sanity client
6. Run `npm run dev` and see it work
7. Create new Sanity client in the loader function in `root.tsx`
8. Run `npm run dev` and see it break

**Expected behavior**

Adding Sanity client does not break anything, and works.

**Actual behavior**

Adding Sanity client throws `TypeError: globalThis.XMLHttpRequest is not a constructor` and does not work.

**Comment by frehner** [comment]
There appears to be some devs that have found downgrading to `5.2.2` has fixed things for them.

**Comment by dylanmcgowan** [comment]
> There appears to be some devs that have found downgrading to `5.2.2` has fixed things for them.

Downgrading did not work for me :(

**Comment by christiandunbar** [comment]
@LukasMurdock @dylanmcgowan 

The following packages and versions for me locally

```
"@remix-run/react": "1.14.0"
"@sanity/block-content-to-react": "3.0.0"
"@sanity/client": "5.3.0"
"@sanity/types": "2.35.0"
"@shopify/cli": "3.44.1"
"@shopify/cli-hydrogen": "4.0.9"
"@shopify/hydrogen": "2023.1.6"
"@shopify/remix-oxygen": "1.0.4"
```

It however does not work when deploying to Shopify Oxygen when using the automatically generated Github action file as it uses yarn which causes the same `TypeError: globalThis.XMLHttpRequest is not a constructor` error.

I got the deployment to work when changing from yarn to npm.

![image](https://user-images.githubusercontent.com/11332936/227660039-8204790a-067a-4aa3-b4b4-f10f0793b928.png)

**Comment by dcodrin** [comment]
This is probably the change that introduced the issue https://github.com/sanity-io/client/pull/169.

**Comment by gmisa** [comment]
Tried downgrading to **5.2.2** and replaced yarn with **npm** but still the same issue.  `TypeError: globalThis.XMLHttpRequest is not a constructor`.

**Comment by dcodrin** [comment]
@gmisa you have to make sure to regenerate your yarn.lock file.
Pin the version to 5.3.0 (last confirmed working version) `"@sanity/client": "5.3.0"`. Then regenerate your lock file (note simply running `yarn` will not work you have to generate it by deleting the current one and letting yarn generate a new one).

After this you should be able to start it locally. If you encounter issues during deploy it might be due to caching, check if you can get a clean install of dependencies. My guess is that's why it worked for Christian above because he simply bypassed the yarn cache by using npm.

**Comment by stipsan** [comment]
Hi, there's a test version available (tracked in #181) that lazy loads `@sanity/eventsource` that you can test using:
```bash
npm i --save-exact @sanity/client@lazy-event-source
```
```bash
yarn add --exact @sanity/client@lazy-event-source
```
```bash
pnpm install --save-exact @sanity/client@lazy-event-source
```

Hopefully that'll solve the `TypeError: globalThis.XMLHttpRequest is not a constructor` case 🙇

**Comment by corygibbons** [comment]
Solved it for me, much thanks @stipsan.

**Comment by dylanmcgowan** [comment]
This issue can be closed, upgrading to `@sanity/client@latest` fixes the error.  Thanks so much @stipsan
