### ISSUE TITLE
Type errors

### ISSUE THREAD

**Issue by runeh** [sanity-io/client#18]
The `ObservableTransaction` and `ObservablePatch` types are no longer correct. Projects with `skipLibCheck: false` will likely not compile when using the client.

There are noe test or compile errors, but you get squiggles in the editor.

```
Property 'clone' in type 'ObservablePatch' is not assignable to the same property in base type 'Patch'.
```

[Translated error](https://ts-error-translator.vercel.app/?error=AoJw9gDgpiAuCeACA5AYzAWwwS1sx2AdogtCgPIBGAzjAG4CGlANlMA7KgBb7bWKEwsRA2rVsAc0JNWJMCS5RE1BhiURw0OEiKJKopaSXJ2nHgDoAUIkQAVeGWQBvRAB4ASogC8IwvAB8ABSQsNhghNQAXIgAYtgg1LAAImCoAK5qhLAAsmmwHGGE5BCh4dQAlNFUtCCMLFCuAMoMhLjwKemZsB7+-gDcbp4+LQHBJYVRiACCzMwdGVBZ1Ln5pUXjZZWI1fQyDeYH-Yhja5NxCcmpC1kAkgAmKwXhxadbO7V7rgfmRycT0TM5lcuvdlnknutXlUaLt6l9DgMPN5fKMQhMAPzRABCBkeaxeE0QAB9EGlCHcoAAzIjfXj8QTCUTiKR7OQkBzGFxI4Z+IJosrRc6JeZdPGFAmbaKgTB8BrNVoIEWLbruXqIoYovkbCIA2ZKpZi57aipS8A4Wjwn4DP4C2LxYXA5X3Q2QiZbaXm-YI478nXTPWO253MGrcXG91m2WWo7czU2iKYxA42guiURYmk8lUohQO4RmW0WnmIA)

![Screenshot 2022-08-15 at 10 46 36](https://user-images.githubusercontent.com/64223/184605560-bad88423-36ec-486e-920b-ce398ec20aa0.png)

**Comment by runeh** [comment]
What the error actually means is that the subclass is trying to implement a method from the superclass with an incompatible return type afaict. Simliar to this:

```
export class Foo {
  getName(): string;
}

export class Bar extends Foo {
  getName(): Promise<string>
}
```

**Comment by runeh** [comment]
A whittled down version with what triggers it:

```typescript
import type {Observable} from 'rxjs'

export interface SingleMutationResult {
  foo: string
}

export class Patch {
  commit(options: FirstDocumentIdMutationOptions): Promise<SingleMutationResult>
}

export class ObservablePatch extends Patch {
  commit<R = any>(options: FirstDocumentMutationOptions): Observable<SanityDocument<R>>
}

type FirstDocumentMutationOptions = {
  foo: string
}

type FirstDocumentIdMutationOptions = {
  foo: string
}

export type SanityDocument<T extends Record<string, any> = Record<string, any>> = {
  [P in keyof T]: T[P]
} & {_id: string}
```

**Comment by Kutschfo** [comment]
Hi, I am facing the same issue since yesterday. Any idea, on how to bypass that problem?
What Angular-Version are you using?

**Comment by runeh** [comment]
The bug doesn't rely on angular version. We're not using angular at all. The short term workaround is to set `skipLibCheck: true` in your tsconfig perhaps?
