### ISSUE TITLE
Property '#private' in type 'SanityClient'

### ISSUE THREAD

**Issue by spacedawwwg** [sanity-io/client#182]
```
Argument of type 'import("/project/node_modules/@sanity/types/node_modules/@sanity/client/dist/index").SanityClient' is not assignable to parameter of type 'import("/project/node_modules/@sanity/client/dist/index").SanityClient'.
  Property '#private' in type 'SanityClient' refers to a different member that cannot be accessed from within type 'SanityClient'
```

Occurs when using `useClient({ apiVersion: '2022-03-13' })` for a value against `import type { SanityClient } from '@sanity/client';`

### Expected 
SanityClient type should be accessible

**Comment by wimbarelds** [comment]
We are also having this issue since our npm updates this week.

**Comment by stipsan** [comment]
This will be resolved with the next release of `sanity`: https://github.com/sanity-io/sanity/pull/4454
