### ISSUE TITLE
`withCredentials` not working in Safari

### ISSUE THREAD

**Issue by robinscholz** [sanity-io/client#183]
We are currently running into Problems with a Nuxt application that has a custom preview mode with a query flag implemented for preview urls coming from a Sanity Studio deployment.

It seems like the `withCredentials` option is simply not working in Safari (tested on MacOs, Safari 16.1 and iOS 16.3.1). If I manually pass a token, the preview works as expected. The previews also work in Chrome.

It seems like Sanity Studio usually creates a  `sanitySession` cookie with the token, whereas in Safari it creates a `__studio_auth_token_${PROJECT_ID}` entry in localStorage. Not sure if this is related, but might be the problem?

Would be great if this could be debugged, let me know if I can provide any other information!

**Comment by imckinnon08** [comment]
Hello, could someone take a look at this issue and provide an update? Thank you.

**Comment by robinscholz** [comment]
This is still a problem with the latest version of the client. Can someone please take a look and fix this?

**Comment by stipsan** [comment]
Unfortunately there isn't anything we can do to fix this as this is not a bug, but a Safari "feature". 
You'll have to implement auth and grab a Content Lake token for the preview session, Safari have effectively killed cookies 😭
