### ISSUE TITLE
TypeError: generateHelpUrl is not a function

### ISSUE THREAD

**Issue by georgebutter** [sanity-io/client#20]
`/node_modules/@sanity/client/lib/warnings.js:21:204`

`var generateHelpUrl = require('@sanity/generate-help-url').generateHelpUrl;`

Seems as though `@sanity/generate-help-url@3.0.0` returns a function that returns a string and does not have a key of `generateHelpUrl`.

**Comment by remisture** [comment]
Same problem here. Anyone have a fix or workaround?

**Comment by stipsan** [comment]
Heya 👋  Good news, we've deprecated `@sanity/client` a [couple of days ago](https://github.com/sanity-io/client/commit/0541e5776748f9954e1a318f91f5e9b3ea2f277d) as part of our larger ESM initiative 😌
If we knew `@sanity/generate-help-url` were causing you folks trouble we would've made a release while at it.

Give me a moment 😉  cc @rexxars I'll just make a 3.3.4 release real quick 🥷

**Comment by stipsan** [comment]
Fix is included here 🎉  https://github.com/sanity-io/client/releases/tag/v3.3.4
