### ISSUE TITLE
webpack SSR bundle failures with node: 

### ISSUE THREAD

**Issue by zanedev** [sanity-io/client#206]
v5.4.2 of client is throwing these errors during build for a gatsby 5.9.0 site React 18. Not sure when the issue occurs but downgrading to latest v4 (v4.0.1) and it goes away. Tried polyfilling it in webpack config but list just keeps growing.

```
 ERROR #98123  WEBPACK.BUILD-HTML

Generating SSR bundle failed

Reading from "node:https" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.

File: node:https


 ERROR #98123  WEBPACK.BUILD-HTML

Generating SSR bundle failed

Reading from "node:http" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.

File: node:http


 ERROR #98123  WEBPACK.BUILD-HTML

Generating SSR bundle failed

Reading from "node:url" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.

File: node:url

```

**Comment by stipsan** [comment]
Could you try:
```js
{
  plugins: [
    {
      resolve: `gatsby-plugin-alias-imports`,
      options: {
        alias: {
          "node:http": "http",
        },
      }
    }
  ]
}
```

**Comment by zanedev** [comment]
Didn't seem to help unfortunately, same error after installing the plugin and adding to gatsby-config plugins array.

**Comment by gorceag** [comment]
> Didn't seem to help unfortunately, same error after installing the plugin and adding to gatsby-config plugins array.

Hey @zanedev, did you solve this in any way? I'm experiencing the same issue after upgrading Sanity.

**Comment by Hahlh** [comment]
@zanedev Thank you very much for raising this issue here. 

We were actually also experiencing this issue ("node:url" and "node:https") and were able to work around it by downgrading to `@sanity/client@^v4`.

Afterwards we were able to use `preview-kit` with `createClient` successfully for previews with Gatsby. 

Much appreciated!
