### ISSUE TITLE
Configure client to only pull back published data

### ISSUE THREAD

**Issue by ptimson** [sanity-io/client#235]
I'm using an authenticated dataset. So when I pull back data it includes both drafts and published documents. 

I would like to have an option for the client to only pull back published documents. 

This means in the preview mode it can pull back everything (how it currently behaves) and in normal mode it will only use the published documents.

Currently, the way to achieve this is to add it to the queries but this adds extra complexity: https://www.sanity.io/docs/drafts#ebfb408fa9b6

The current workaround is to append `slug.current == $slug && (!$publishedOnly || !(_id in path('drafts.**')))` to each of my document selectors which isn't very nice:
```
export const pageBySlugQuery = groq`
  *[_type == "page" && slug.current == $slug && (!$publishedOnly || !(_id in path('drafts.**')))][0]
`

// Then use params: { publishedOnly: true }
```

**Comment by stipsan** [comment]
Hi! We're testing a new feature on `apiVersion: 'X'` that you can use starting from [v6.1.0](https://github.com/sanity-io/client/releases/tag/v6.1.0) called `perspective`. `perspective: 'published'` should give you the behaviour you're describing. There's also `perspective: 'previewDrafts'` that will dedupe documents and return draft documents over the published ones, if they exist.

Note that this is a very experimental and undocumented feature that we're testing and gathering feedback on. It might change, it might be removed, so don't use it in production or rely on it! :)
