### ISSUE TITLE
Sanity Node JS client typescript error for ObservableTransaction Type

### ISSUE THREAD

**Issue by ArefEghbaliDev** [sanity-io/client#25]
Hi, 
I'm trying to compile a typescript node js project and sanity IO client throws these two errors:

"Property 'commit' in type 'ObservableTransaction' is not assignable to the same property in base type 'Transaction' "
"Property 'clone' in type 'ObservablePatch' is not assignable to the same property in base type 'Patch' "

`node_modules/@sanity/client/sanityClient.d.ts:387:3 - error TS2416: Property 'clone' in type 'ObservablePatch' is not assignable to the same property in base type 'Patch'.
  Type '() => ObservablePatch' is not assignable to type '() => Patch'.
    Call signature return types 'ObservablePatch' and 'Patch' are incompatible.
      The types returned by 'commit(...)' are incompatible between these types.
        Type 'Observable<SanityDocument<any>>' is missing the following properties from type 'Promise<SanityDocument<any>>': then, catch, finally, [Symbol.toStringTag]    

387   clone(): ObservablePatch`

`node_modules/@sanity/client/sanityClient.d.ts:560:3 - error TS2416: Property 'commit' in type 'ObservableTransaction' is not assignable to the same property in base type 'Transaction'.  
  Type '{ <R>(options: TransactionFirstDocumentMutationOptions): Observable<SanityDocument<R>>; <R>(options: TransactionAllDocumentsMutationOptions): Observable<...>; (options: TransactionFirstDocumentIdMutationOptions): Observable<...>; (options: TransactionAllDocumentIdsMutationOptions): Observable<...>; (options?: BaseMu...' is not assignable to type '{ <R>(options: 
TransactionFirstDocumentMutationOptions): Promise<SanityDocument<R>>; <R>(options: TransactionAllDocumentsMutationOptions): Promise<...>; (options: TransactionFirstDocumentIdMutationOptions): Promise<...>; (options: TransactionAllDocumentIdsMutationOptions): Promise<...>; (options?: BaseMutationOption...'.

560   commit(options: TransactionFirstDocumentIdMutationOptions): Observable<SingleMutationResult>`

and this is my tsconfig.json:
`{
  "compilerOptions": {
    "target": "es6",
    "lib": ["es2017", "esnext.asynciterable", "es2019", "ES2020.Promise"],
    "typeRoots": ["./node_modules/@types"],
    "allowSyntheticDefaultImports": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "forceConsistentCasingInFileNames": true,
    "moduleResolution": "node",
    "module": "commonjs",
    "pretty": true,
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./src",
    "rootDir": ".",
    "allowJs": true,
    "noEmit": false,
    "esModuleInterop": true,
    "incremental": true
  },
  "include": ["./src/**/*", "./types"],
  "exclude": ["node_modules", "tests"]
}
`

**Comment by rexxars** [comment]
We'll have a patch out for this on Monday - in the meantime, try setting `skipLibCheck` to `true` in your tsconfig: https://www.typescriptlang.org/tsconfig#skipLibCheck
