### ISSUE TITLE
`perspective` not always included in query

### ISSUE THREAD

**Issue by corygibbons** [sanity-io/client#254]
I'm experiencing an issue where sometimes including `perspective: published` in my client config still returns the results of a `raw` query.

Digging into it a bit it seems like if the groq query is too large the `perspective` param isn't included. "Too large" seems to be past the threshold where the `query` is included in the body of the request instead of as a query param.

Using `v6.1.5`

**Comment by mwain** [comment]
Hi @corygibbons, 

Thanks for reporting this and diving into the details, your effort really helped.

We have fixed the issue in #255 and have rolled out a new version, v6.1.6.
Please give it a try and let us know if it resolves the problem for you.
