### ISSUE TITLE
Perspective param not taken into account when using POST method

### ISSUE THREAD

**Issue by LouisJackson** [sanity-io/client#420]
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**

`perspective` param is not taken into account when long query is sent and POST method is being used.

**To Reproduce**

1. Send a long query using POST method and append perspective params in fetch URL. For instance: https://PROJECT_ID.api.sanity.io/v2023-04-24/data/query/[DATASET]?perspective=previewDrafts
2. Observe the published data being returned and not the draft data.

**Expected behavior**

Draft Data of query should be fetched.

**Screenshots**

**Which versions of Sanity are you using?**

@sanity/cli (global)                   3.12.2 (latest: 3.20.1)
@sanity/color-input                     3.1.0 (up to date)
@sanity/document-internationalization   2.0.1 (latest: 2.0.2)
@sanity/icons                           2.4.1 (latest: 2.7.0)
@sanity/schema                         3.17.0 (latest: 3.20.1)
@sanity/ui                              1.9.3 (up to date)
@sanity/vision                         3.16.7 (latest: 3.20.1)
sanity                                 3.12.2 (latest: 3.20.1)

**What operating system are you using?**

MacOS

**Which versions of Node.js / npm are you running?**

9.6.7
v18.17.0

**Additional context**

**Security issue?**

Any security issues should be submitted directly to [security@sanity.io](mailto:security@sanity.io). In order to determine whether you are dealing with a security issue, ask yourself these two questions:

- Can I access something that's not mine, or something I shouldn't have access to?
- Can I disable something for other people? If the answer to either of those two questions are "yes", then you're probably dealing with a security issue. Note that even if you answer "no" to both questions, you may still be dealing with a security issue, so if you're unsure, just email us at [security@sanity.io](mailto:security@sanity.io.

**Comment by geball** [comment]
Is the request authenticated? If not, it would only be able to return publicly-accessible documents (i.e., published documents on the root path).

**Comment by LouisJackson** [comment]
> Is the request authenticated? If not, it would only be able to return publicly-accessible documents (i.e., published documents on the root path).

It is, and it does work with smaller queries using GET method.

**Comment by LouisJackson** [comment]
> Is the request authenticated? If not, it would only be able to return publicly-accessible documents (i.e., published documents on the root path).

Ah actually was the issue. Works now. Thanks :)
