### ISSUE TITLE
Type incompatibility with `nodenext` module resolution

### ISSUE THREAD

**Issue by james-camilleri** [sanity-io/client#49]
I'm attempting to update some of my TypeScript codebases to use the named exports functionality in `package.json`.  There seems to be an issue with the type definitions for the client when TypeScript is configured to use `nodenext` module resolution. The issue seems to stem from the final `export default SanityClientConstructor` line in the `sanityClient.d.ts` file: https://github.com/sanity-io/client/blob/12fb34e76e37c3dfb62c8f21f457c7c6a7236703/sanityClient.d.ts#L2256. Since the client is not marked as a `module` in package.json, TypeScript parses it as a CommonJS file. Given that `export default` is not valid CJS syntax, TypeScript chokes up on it and fails to properly infer types - this is by design on TypeScript's part I believe.

Correcting the export to the CJS style `export = SanityClientConstructor` seems to solve this problem, although I haven't yet tested for any regression errors. Should I open a PR to look into correcting this?

**Comment by stipsan** [comment]
Hi, could you try with `npm i @sanity/client@^5.0.0` to see if it resolves it?

**Comment by stipsan** [comment]
We're now shipping with `"type": "module"` in our package json
