### ISSUE TITLE
Same query in Studio Vision and @sanity/client with different results

### ISSUE THREAD

**Issue by WebShapedBiz** [sanity-io/client#534]
**Describe the bug**
I'm trying to do custom validation on the boolean field uniqueness, and while being stuck deciding what to do next, I spotted that the same GROQ query produces different results in Studio Vision and `@sanity/client`. I have `useCdn: false` option in the client configuration just to rule out potential cache issues. Also, I have the latest versions of everything at the time of writing this.

**To Reproduce**
I have a boolean field `breakingnews` in schema type `video` and need to allow only one such video.
The query that I'm using for testing my custom validation is very simple `*[_type == 'video' && breakingnews == true]`. The test scenario is that I have one published video with `breakingnews == true` and I try to add another one. Adding another video with `breakingnews == true` creates a new draft document and here the difference becomes visible.

In Sanity Vision (API v2022-03-07) when I add a new draft it becomes immediately visible in the response, that is I receive two objects in the response, one published and one draft, as I believe I should.

In my custom validation code, I use the same query:
```
validation: Rule => Rule.custom(async () => {
  const query = groq`*[_type == 'video' && breakingnews == true]`
  const docs = await client.fetch(query)
  console.log(docs.length)
  return docs.length > 1 ? 'Value is not unique' : true
})
```

Here I can see in the console that when adding the new draft with `breakingnews == true`, the same query returns only one document, the published one, and only when I publish that new document does the console log show 2 documents.

**Expected behavior**
I'm not yet that experienced with Sanity, so please forgive me if I'm not getting things right, but I would expect that in my simple scenario, Studio Vision and @sanity/client should have the same response to the same query. 

I know this is a lengthy one so thank you for your time and effort.

Cheers.

**Comment by bobinska-dev** [comment]
Hello @WebShapedBiz 
1. Inside of the studio you need to use the client provided by the context (see this doc article) -> this client will the authenticated and will then be able to fetch drafts. 
2. When you want to also include drafts you can use the perspective `previewDrafts` 

Your code should look something like this: 

```
      validation: (Rule) =>
        Rule.custom( async (value, context) => {
          const query = groq`*[_type == 'video' && breakingnews == true]`
          const client = context.getClient({apiVersion: '2021-03-25'}).withConfig({ perspective: 'previewDrafts'})
          // the rest if your valudation
        }),
```

Please join our [community slack ](https://slack.sanity.io/) and ask questions like these in the #help channel :)

**Comment by WebShapedBiz** [comment]
Thank you @bobinska-dev for your time and effort in helping me.

**Comment by bobinska-dev** [comment]
Wonderful it helped you! I thought we had that better documented, but could not find it outside of the TS docs, so I also filed for that to be done! 

Happy coding

**Comment by WebShapedBiz** [comment]
Cheers.
