### ISSUE TITLE
invalid `module` export condition breaks nuxt

### ISSUE THREAD

**Issue by danielroe** [sanity-io/client#622]
**Describe the bug**

Previously I raised https://github.com/sanity-io/client/issues/308 to report an export condition that was breaking nuxt/nitro builds with `@sanity/client`. This was resolved in https://github.com/sanity-io/client/pull/318.

However, [this commit](https://github.com/sanity-io/client/commit/76d5e247a9226c2709c9c306ced04e3831915286) has reintroduced the original issue.

cc: @pi0

**To Reproduce**

https://stackblitz.com/edit/github-p4ek33

**Comment by NikhilVerma** [comment]
I am facing the same issue, I am working around it by patching @sanity/client using `pnpm patch @sanity/client`

```patch
diff --git a/package.json b/package.json
index 4f625cbe72e865e4181ed18d5d45d497a55f7915..7622e141bbf4eb17db168988deda59650b61088c 100644
--- a/package.json
+++ b/package.json
@@ -38,7 +38,6 @@
       "edge-light": "./dist/index.browser.js",
       "worker": "./dist/index.browser.js",
       "source": "./src/index.ts",
-      "module": "./dist/index.js",
       "require": "./dist/index.cjs",
       "node": {
         "import": "./dist/index.cjs.js"
@@ -66,7 +65,6 @@
       "worker": "./dist/stega.browser.js",
       "source": "./src/stega/index.ts",
       "module": "./dist/stega.js",
-      "require": "./dist/stega.cjs",
       "node": {
         "import": "./dist/stega.cjs.js"
       },
```
