### ISSUE TITLE
unexpected token "==", expected expression

### ISSUE THREAD

**Issue by empato-limited** [sanity-io/client#641]
What am i missing ... after the last update this does not work anymore?
```
client.fetch(`*[_type == "post"]`)
```
i get
```
[Error: unexpected token "==", expected expression]
```

**Comment by stipsan** [comment]
@empato-limited could you try https://github.com/sanity-io/client/releases/tag/v6.15.5 and see if it fixes it?

**Comment by stipsan** [comment]
Closing, assuming it's resolved
