### ISSUE TITLE
Error: no query with @sanity/client v6.15.20 in React Native

### ISSUE THREAD

**Issue by shukerullah** [sanity-io/client#774]
I'm experiencing an issue with the latest versions of __@sanity/client__ (v6.15.20) when used in a React Native project.

**To Reproduce**
Update __@sanity/client__ to the latest version (v6.15.20) in your React Native project.

**Expected behavior**
The app should display a list of posts fetched from Sanity using the provided query.

**Actual Behavior**
When using __v6.15.20__, I encounter a "no query" error. However, the same code functions correctly when I downgrade to __v6.4.5__.

**Screenshots**
![Screenshot_1714645359](https://github.com/sanity-io/client/assets/963765/be66a774-3119-442d-b5da-8c9b5d3c6b7d)

**Which versions of Sanity are you using?**
v6.15.20

**Which versions of React Native are you using?**
v0.74.0

**What operating system are you using?**
Windows

**Which versions of Node.js / npm are you running?**
v21.0.0

**Comment by rexxars** [comment]
Which version of React Native are you using?

**Comment by shukerullah** [comment]
React Native: 0.74.0
