### ISSUE TITLE
The Sanity client API call is failing on all older versions of Safari browsers (version 16 or older) (queryParseError).

### ISSUE THREAD

**Issue by Santheepkumar** [sanity-io/client#793]
**Description**
The Sanity client API call is failing on all non-latest Safari browsers. (queryParseError).
I'm not sure about the cause. The strange thing is, this issue only occurs on Safari browsers that are not the latest version. It works fine on all other browsers and the latest Safari. Can anyone help with this? This issue started occurring recently, and our users are experiencing it regularly. Quick help would be appreciated.
The issue is not happening on localhost; it's only occurring on production and specifically on Safari browsers with versions older than 17.

**To Reproduce**

1. Query using sanity client (any version) 
2. Sanity client query API call failing on only non-latest Safari browsers (version 16 or older)

**Note:** The formatting of query Request URL differs from that of other browsers and all older versions of Safari.

**Query Request URL**
URL: https://tq4wzdvz.apicdn.sanity.io/v1/data/query/production?query=*%5B_type%2B%3D%3D%2B%22location%22%2B%26%26%2BisBookable%2B%3D%3D%2Btrue%2B%26%26%2B%21%28_id%2Bin%2Bpath%28%27drafts.**%27%29%29%5D%7B%0A%2B%2Bid%2C%0A%2B%2Bname%2C%0A%2B%2Btimezone%2C%0A%2B%2BopenDate%2C%0A%2B%2B%22mapImg%22%3A%2BfeaturedImage.asset-%3Eurl%2C%0A%2B%2BenableMembershipFlow%2C%0A%2B%2BenableGroupBooking%2C%0A%2B%2BenableGhostBooking%2C%0A%2B%2BadvanceBookingLimit%2C%0A%2B%2Baddress%2C%0A%2B%2BmarketingSupport%7B%0A%2B%2B%2B%2B...%2C%0A%2B%2B%2B%2BconfirmationPromo%7B%0A%2B%2B%2B%2B%2B%2Bheadline%2C%0A%2B%2B%2B%2B%2B%2Bsubheading%2C%0A%2B%2B%2B%2B%2B%2BofferCode%2C%0A%2B%2B%2B%2B%2B%2B%27bannerColor%27%3A%2BbgColor.hex%2C%0A%2B%2B%2B%2B%2B%2B%27textColor%27%3A%2BtextColor.hex%0A%2B%2B%2B%2B%7D%0A%2B%2B%7D%2C%0A%2B%2Bcontact%7B%0A%2B%2B%2B%2B...%2C%0A%2B%2B%2B%2Bavailability%5B%5D%7B%0A%2B%2B%2B%2B%2B%2Bday%2C%0A%2B%2B%2B%2B%2B%2BavailableTimes%5B%5D%7B%0A%2B%2B%2B%2B%2B%2B%2B%2Bfrom%2C%0A%2B%2B%2B%2B%2B%2B%2B%2Bto%0A%2B%2B%2B%2B%2B%2B%7D%0A%2B%2B%2B%2B%7D%0A%2B%2B%7D%2C%0A%7D&returnQuery=false
Status: 400 Bad Request
Source: Network
Address: 34.102.190.179:443
Initiator:
browser-request.ts:113

**Query Response**
```json{
    "error": {
        "description": "unexpected token \"==\", expected expression",
        "end": 10,
        "query": "*[_type+==+\"location\"+&&+isBookable+==+true+&&+!(_id+in+path('drafts.**'))]{\n++id,\n++name,\n++timezone,\n++openDate,\n++\"mapImg\":+featuredImage.asset->url,\n++enableMembershipFlow,\n++enableGroupBooking,\n++enableGhostBooking,\n++advanceBookingLimit,\n++address,\n++marketingSupport{\n++++...,\n++++confirmationPromo{\n++++++headline,\n++++++subheading,\n++++++offerCode,\n++++++'bannerColor':+bgColor.hex,\n++++++'textColor':+textColor.hex\n++++}\n++},\n++contact{\n++++...,\n++++availability[]{\n++++++day,\n++++++availableTimes[]{\n++++++++from,\n++++++++to\n++++++}\n++++}\n++},\n}",
        "start": 8,
        "type": "queryParseError"
    }
}
```

**Query**
```ts
const locationQuery = `*[_type == "location" && isBookable == true && !(_id in path('drafts.**'))]{
  id,
  name,
  timezone,
  openDate,
  "mapImg": featuredImage.asset->url,
  enableMembershipFlow,
  enableGroupBooking,
  enableGhostBooking,
  advanceBookingLimit,
  address,
  marketingSupport{
    ...,
    confirmationPromo{
      headline,
      subheading,
      offerCode,
      'bannerColor': bgColor.hex,
      'textColor': textColor.hex
    }
  },
  contact{
    ...,
    availability[]{
      day,
      availableTimes[]{
        from,
        to
      }
    }
  },
}`
```

**Querying Function**
```ts
export const getLocations = async (formatFn = formatData) => {
  const response: LocationPlace[] = await SanityClient.fetch(
    locationQuery
  ).catch(console.error)
  if (response) {
    return formatFn(response)
  } else {
    console.error(response)
    throw new Error(response)
  }
}
```

**Sanity Client**
```ts
import { createClient } from '@sanity/client'
export default createClient({
  projectId: 'tq4wzdvz',
  dataset:
    process.env.REACT_APP_ENV === 'development' ? 'development' : 'production',
  token: process.env.REACT_APP_SANITY_TOKEN,
})
```

**Expected behavior**
Should query the data on all browsers

**Screenshots**
![Screenshot 2024-05-06 at 3 53 32 PM](https://github.com/sanity-io/client/assets/41126042/3fa4a8b1-00bd-4f83-94a9-47a7885bfe8e)

**What operating system are you using?**
Mac OS - (Issues occur on any non-latest versions of Safari on macOS)

**Which versions of Node.js / npm are you running?**
16+

**Comment by rexxars** [comment]
Can you give some more context?

- What is the URL/query that is failing?
- What is the response code for the request, or error if it's a network error?

**Comment by Santheepkumar** [comment]
> Can you give some more context?
> 
> * What is the URL/query that is failing?
> * What is the response code for the request, or error if it's a network error?

The formatting of query request URL differs from other browsers and all older versions of Safari.
@rexxars Here are the details,


**Request**
URL: https://tq4wzdvz.apicdn.sanity.io/v1/data/query/production?query=*%5B_type%2B%3D%3D%2B%22location%22%2B%26%26%2BisBookable%2B%3D%3D%2Btrue%2B%26%26%2B%21%28_id%2Bin%2Bpath%28%27drafts.**%27%29%29%5D%7B%0A%2B%2Bid%2C%0A%2B%2Bname%2C%0A%2B%2Btimezone%2C%0A%2B%2BopenDate%2C%0A%2B%2B%22mapImg%22%3A%2BfeaturedImage.asset-%3Eurl%2C%0A%2B%2BenableMembershipFlow%2C%0A%2B%2BenableGroupBooking%2C%0A%2B%2BenableGhostBooking%2C%0A%2B%2BadvanceBookingLimit%2C%0A%2B%2Baddress%2C%0A%2B%2BmarketingSupport%7B%0A%2B%2B%2B%2B...%2C%0A%2B%2B%2B%2BconfirmationPromo%7B%0A%2B%2B%2B%2B%2B%2Bheadline%2C%0A%2B%2B%2B%2B%2B%2Bsubheading%2C%0A%2B%2B%2B%2B%2B%2BofferCode%2C%0A%2B%2B%2B%2B%2B%2B%27bannerColor%27%3A%2BbgColor.hex%2C%0A%2B%2B%2B%2B%2B%2B%27textColor%27%3A%2BtextColor.hex%0A%2B%2B%2B%2B%7D%0A%2B%2B%7D%2C%0A%2B%2Bcontact%7B%0A%2B%2B%2B%2B...%2C%0A%2B%2B%2B%2Bavailability%5B%5D%7B%0A%2B%2B%2B%2B%2B%2Bday%2C%0A%2B%2B%2B%2B%2B%2BavailableTimes%5B%5D%7B%0A%2B%2B%2B%2B%2B%2B%2B%2Bfrom%2C%0A%2B%2B%2B%2B%2B%2B%2B%2Bto%0A%2B%2B%2B%2B%2B%2B%7D%0A%2B%2B%2B%2B%7D%0A%2B%2B%7D%2C%0A%7D&returnQuery=false
Status: 400 Bad Request
Source: Network
Address: 34.102.190.179:443
Initiator:
browser-request.ts:113

**Response**
```json{
    "error": {
        "description": "unexpected token \"==\", expected expression",
        "end": 10,
        "query": "*[_type+==+\"location\"+&&+isBookable+==+true+&&+!(_id+in+path('drafts.**'))]{\n++id,\n++name,\n++timezone,\n++openDate,\n++\"mapImg\":+featuredImage.asset->url,\n++enableMembershipFlow,\n++enableGroupBooking,\n++enableGhostBooking,\n++advanceBookingLimit,\n++address,\n++marketingSupport{\n++++...,\n++++confirmationPromo{\n++++++headline,\n++++++subheading,\n++++++offerCode,\n++++++'bannerColor':+bgColor.hex,\n++++++'textColor':+textColor.hex\n++++}\n++},\n++contact{\n++++...,\n++++availability[]{\n++++++day,\n++++++availableTimes[]{\n++++++++from,\n++++++++to\n++++++}\n++++}\n++},\n}",
        "start": 8,
        "type": "queryParseError"
    }
}
```

**Query**
```ts
const locationQuery = `*[_type == "location" && isBookable == true && !(_id in path('drafts.**'))]{
  id,
  name,
  timezone,
  openDate,
  "mapImg": featuredImage.asset->url,
  enableMembershipFlow,
  enableGroupBooking,
  enableGhostBooking,
  advanceBookingLimit,
  address,
  marketingSupport{
    ...,
    confirmationPromo{
      headline,
      subheading,
      offerCode,
      'bannerColor': bgColor.hex,
      'textColor': textColor.hex
    }
  },
  contact{
    ...,
    availability[]{
      day,
      availableTimes[]{
        from,
        to
      }
    }
  },
}`
```

**Querying Function**
```ts
export const getLocations = async (formatFn = formatData) => {
  const response: LocationPlace[] = await SanityClient.fetch(
    locationQuery
  ).catch(console.error)
  if (response) {
    return formatFn(response)
  } else {
    console.error(response)
    throw new Error(response)
  }
}
```


**Sanity Client**
```ts
import { createClient } from '@sanity/client'
export default createClient({
  projectId: 'tq4wzdvz',
  dataset:
    process.env.REACT_APP_ENV === 'development' ? 'development' : 'production',
  token: process.env.REACT_APP_SANITY_TOKEN,
})

**Comment by rexxars** [comment]
Thank you. I am still struggling to reproduce - using `@sanity/client@6.17.2`, the following:

```js
import {createClient} from '@sanity/client'

const client = createClient({
  projectId: 'espenhov',
  dataset: 'production',
  useCdn: true
})

const locationQuery = `*[_type == "location" && isBookable == true && !(_id in path('drafts.**'))]{
  id,
  name,
  timezone,
  openDate,
  "mapImg": featuredImage.asset->url,
  enableMembershipFlow,
  enableGroupBooking,
  enableGhostBooking,
  advanceBookingLimit,
  address,
  marketingSupport{
    ...,
    confirmationPromo{
      headline,
      subheading,
      offerCode,
      'bannerColor': bgColor.hex,
      'textColor': textColor.hex
    }
  },
  contact{
    ...,
    availability[]{
      day,
      availableTimes[]{
        from,
        to
      }
    }
  },
}`

client.fetch(locationQuery)
  .then(response => console.log(response))
  .catch(err => console.error(err))
```

Seems to work fine in Safari 17.4.1, Safari 15.6, Safari 14.1.2, Chrome and Firefox.

Which version of `@sanity/client` are you running?

**Comment by Santheepkumar** [comment]
> Thank you. I am still struggling to reproduce - using `@sanity/client@6.17.2`, the following:
> 
> ```js
> import {createClient} from '@sanity/client'
> 
> const client = createClient({
>   projectId: 'espenhov',
>   dataset: 'production',
>   useCdn: true
> })
> 
> const locationQuery = `*[_type == "location" && isBookable == true && !(_id in path('drafts.**'))]{
>   id,
>   name,
>   timezone,
>   openDate,
>   "mapImg": featuredImage.asset->url,
>   enableMembershipFlow,
>   enableGroupBooking,
>   enableGhostBooking,
>   advanceBookingLimit,
>   address,
>   marketingSupport{
>     ...,
>     confirmationPromo{
>       headline,
>       subheading,
>       offerCode,
>       'bannerColor': bgColor.hex,
>       'textColor': textColor.hex
>     }
>   },
>   contact{
>     ...,
>     availability[]{
>       day,
>       availableTimes[]{
>         from,
>         to
>       }
>     }
>   },
> }`
> 
> client.fetch(locationQuery)
>   .then(response => console.log(response))
>   .catch(err => console.error(err))
> ```
> 
> Seems to work fine in Safari 17.4.1, Safari 15.6, Safari 14.1.2, Chrome and Firefox.
> 
> Which version of `@sanity/client` are you running?

@rexxars I am using @sanity/client ^6.4.0. I have also tried the latest version ^6.15.4, but encountered the same issue. The query works fine on the local server, but it fails on production.

For your reference, please check the following site on Chrome and older versions of Safari. You will notice that the sanity API call fails on older Safari browsers.
**Site:** https://webbooking.dev.heydayskincare.com/
**Note:** Simply open this site on old safari browsers(any non latest), observe the sanity API call in the network tab.

![Screenshot 2024-05-06 at 2 58 47 PM](https://github.com/sanity-io/client/assets/41126042/f8301b7a-a4f5-4303-a9e7-8a4fba38926b)

**Comment by rexxars** [comment]
> I am using @sanity/client ^6.4.0. I have also tried the latest version ^6.15.4, but encountered the same issue. The query works fine on the local server, but it fails on production.

The fact that it works locally but not remotely sounds very odd - I am wondering if there is a mismatch in dependency versions here. The error sounds like something we fixed a few versions back in the Sanity client, through the dependency `get-it`.

Might be jumping to conclusions here, but there may be a lock file that keeps your production environment on an old version? I'd look at any lockfile to see if you are running [get-it@v8.4.28](https://github.com/sanity-io/get-it/releases/tag/v8.4.28) or later.

**Comment by Santheepkumar** [comment]
@rexxars Yes, it was due to a mismatch in the get-it package in the lock file. I have updated the @sanity/client to latest and the lock file. It fixes the issue. Thank you so much for the support; I really appreciate it. ❤️
