### ISSUE TITLE
v3.1.0 has broken React Native apps without `Intl` support

### ISSUE THREAD

**Issue by fiznool** [sanity-io/client#8]
#2 introduced a new dependency `event-source-polyfill`, which [uses the `Intl` API in one place](https://github.com/Yaffle/EventSource/blob/master/src/eventsource.js#L1032-L1044). Whilst this API is present in most browser implementations, some JavaScript environments do not include support for `Intl` out of the box - for example, React Native.

I don't know if this package is intended for environments such as React Native? If so, there should maybe be an item in the documentation mentioning that a polyfill for Intl is needed here too. It does however seem a shame that a single line in a third party library can bring down an app, and require a large polyfill...

**Comment by rexxars** [comment]
Could you try v3.2.2? I've pinned the polyfill to an older version which does not use the `Intl` API for now. Will reopen if still an issue.
