### ISSUE TITLE
Proposal for runtime safe typed GROQ

### ISSUE THREAD

**Issue by stipsan** [sanity-io/client#89]
# [TypeScript Playground example implementation](https://tsplay.dev/N5Oy5W)

# Situation

It's useful to type GROQ responses (`client.fetch`) in a way that's runtime safe. 
It brings a lot of value as users can make sure the way they're using the data they `client.fetch` are safe from runtime bugs and there's no risk of unexpected errors.
Providing typings on the responses also gives auto-complete support for them so people can write their app code much faster and with less risk of typos.

# Complication

What we offer today is just a generic that lets you specify the response:
```ts
const data = await client.fetch<[title: string]{}>(`*[]{title}`)
// data is typed to `{title: string}[]`
```
But `client` isn't runtime checking this so it's possible that the dataset contains documents that don't define `title`, or maybe sets it to `null`.
Which could lead to runtime errors that TypeScript isn't catching since it's trusting the typings provided to the generic to be "truth":

```ts
data.map(({title}) => data.title.toUpperCase()) // this can throw at runtime if `title` is `null` or `undefined`
```

# Question

How can we offer runtime safety, or at least make it easier for other libraries to provide it?
Can we offer it in a way that doesn't increase the bundle size for people that won't use this feature?

# Answer

Libraries like [groqd](https://github.com/FormidableLabs/groqd) have started using the convention of taking a GROQ string as input, and output an object like: `{query: string, schema: {parse(data: unknown): TypesafeResponse}}`.

We can support this convention, making it very ergonomic for libraries like `groqd` to provide the heavy lifting while the Sanity Client stays lightweight.

Suggested API:
```ts
import {createClient} from '@sanity/client'

const client = createClient()

const custom = await client.fetch({
  query: `count(*)`,
  schema: {
    parse(data: unknown): number {
      if (isNumber(data)) {
        return data
      }
      throw new TypeError(`data isn't a number`)
    },
  },
})

function isNumber(data: unknown): data is number {
  return Number.isFinite(data)
}
```

The reason why it makes sense to use `{query: string, schema: {parse(data: unknown): TypedResponse}}` as opposed to a simpler `{query: string, schema(data: unknown): TypedResponse}` or `{query: string, parse(data: unknown): TypedResponse}` is it makes it easier for libraries to support letting userland customise the parser. They might want narrower types than their library provides out of the box, maybe widen them or perhaps coerce date strings to `Date` instances.

There's more examples exploring this in the [playground]. As well as the companion [codesandbox].

[playground]: https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&useDefineForClassFields=true&esModuleInterop=false&moduleResolution=99&target=99&module=199&allowSyntheticDefaultImports=false&exactOptionalPropertyTypes=true&suppressImplicitAnyIndexErrors=false&isolatedModules=false&noPropertyAccessFromIndexSignature=true&preserveValueImports=false&noImplicitOverride=false#code/PTAEAEDMEsBsFMB2BDAtvAXKaiAOBXAFwDpCBnAKGlVwHsAnQ0QgT13lAG9QAvUAX1CR6tVKADkPWgBNxFKokLx6kZAGMOARXzKWABWT0yyrhVChch4wAppyQsiz5EAa0S0A7ogCUT1+68KfgUlFXUOABU2eGltXVNzAEcdehYsMkJ6HABzM1AyNQALeFRHUDjUgyNlIPlIZzVCaFpEbDIo9liUlmtk3XTMnNAAH1AOmIqWX1A+1Lax6K74zjz6eEJ8elbWdlpIGe7QAEIAXhOJDKzEbLlgijVYZDIyUABlZERoVgBhWGgkJgrcxPFiINRCdZFAA8ACVQOcPiwAHy9boDK7ZaZ6ESoaDGWFIvIgsEQwjQzSgeAADyUiGkL3GS1SKLy5h2EzR5TyWJxePgsPWm0Q4yh7L2zEWkwA2uICsVSuIALoyyzVJVIwnAsig8GQSGFKEReGgREs8xJTlG6m0+kLTqTUAAfjGoHROW5WGxoj5hspNKQtsZDudMMFWxFERlcpKyCVKqs8HVrrGSIS5rULQybUZxrxQe6qN03lZoAziCzuBEACt4I0AJLSY2SAAM0lwPGQACNCnJzaXM0w7A5jExzuJKzJ8I1mohe+mBybcNAAGrKMgzpsANwATM3twBGAC0zYAzIftwBWOfmMtZzawY2IeAeUAAVRhABlrCXzAADQqEIQuBkBgIAACScBONb1tI-DEMgS5qNIiDEGQHxfCwxDNMAEEISua4zvwwBDsgwCzCwOGcCRI78L+JbFn296ofAhhFFUaBkMxhDWOI5HiAANNmixOgcujEORybkQx87lkwawvAiHjIF8pJFNY97STeC7cPJ+CwEwgiKcpcnwJxVZkC01iaaAawbFsQmdCJ5GoUUMbEKqNi6fp3jJl5hB5MEdwgGMhR4kIDRNC08zUrWRAxNg+wsLQ+CgKFTAws4FDErqEUbvQzhNOgVlpretAIMQ2QiPguA8flijUPAVniNJmQsGmWmyaWfwAo+z5vOhPzdYoVnyH2t5MEoGT7sayBKSpDz-IoxB6mSBqIPgqCdsoKK-hmBXWAAVN4v7WaV5VPMYjDWAAchtW30FhZAAGI4F8jWTYQ+7eIJ4gfdNYXIKA62bcozUlsFfaQ1D0NQwAeo6o0yVmH3bjNc1MAtALLfq1hApD5FYLtyXDUdv78T++SuaUWB41DHmNSRfhuJ4PhYMD93tdD9RgpFrR4rdIP0LY9hlM4zNeNMJHzOzJi0zDNlhq0Av3Y9L2fEowsONZUPBPLCWgNY-N3comvIN4PlyzDtlCqAJEU32uvy4QhQiC+T4vuMACi9AiELv5S3is5MIDMv0Cd9sCOTOtR+a-CnZmZXwPBzzKNxyvKKrr0ayj30SCj8wh8b9Bg32EN6+XcMIyW43MKZhAnmjxldYtJArWpluiakhMHVKAD67LwucABEna0LQLilPQLhD8qzaKpw-fRLRMd9tG1Oc329Om0zASs1woCL+wWDiKP4+Ty44gCBvkPc9OUV4gAQmPE+GC42+gGLu+SyL8zcIfmASFPi-Kel9BAdyhtbey34K5smiOKKWZwxy0E7NBQgl8ABk6CI5Qylqcc461YAPkwdgyG4h-6XxwLbH+xCYGgAAPIoNrCQFw8AWBkFNt4YgCBrjO0HucfcJDzDa0ho7GG0B9iGzIE-M+r8OEW0EQrOyrQ7Z6zuHrZ2rsgZ9S9j7Bg0Dy7+x-oHX6JpWjINQaADwXxCjMGKBYEQ7BGBtSHv-IeljrG2I4JcIYI9n7nyHnRPWwjzD8BXrHMJcdq4J3OinK6FMABSrw6HXVQoMa44iegfRPD5RBoBEnJNSRiDJuMD7smPkA8+oDvoUzLnreGFNfp1wboUZAm4ODuFStAaQ0gkCgBYWw68oB47lkTsnS63EalgHAOQQ81J2CNFmbo+goBDyePsbQRxrBQC-l7l038+RCjJVgMhExW1sDbDsTsHIlAoZin2Fk4guzGy5PEM4HpMAnyyDCeYRpGQTyPK6Qco5jYzlvPgB8mIgzixRJGeVWAtBsi1VMnpcgAl95-UEijTFTSBDSUEB85AhC2pyzOknSqyVcCezpCNEJtQKDBQiKFF4t9ealg+CYuq5y1m4EeCwclbzQAtFgG1M57JDyuTUCw6QglOxEGwEwDwDAXAvEoRmHpaE6SjypFgACQEQIgDVaZD40gtVYVoMAMgwB2QFCyLgQgh4eXID5VVOksyqR0EYIeSASqYiHk3OZRAkA1COhgAgE4wAcA9KpKQSg2Vwo8zygVBq7D5EdSzNwRIV8jIqWoB67i4hyWJFkNJGu3A+CGRNOjbANAGD5qkMWvIpbQCFqzZWpuuba08ULTwEu-ZOqY0UL1F87x1YsF+C3EaeRgqvnXNcUAAAtGQttoBrEaMKxtC4-qN3mkNVuOM5YQ3qX2Am2y9ok2OmEteZQeDEFDlZGOkSp1gAALIMA4MgaQm4PgaEbIu6QG7Or52zRjXd2NVq4xLCe38Pd-6D1AL4mRU83GYNtuCnAMR1L0FgN4We89-78V7moNY9gYgAEFCD8SaIQBA-F7zLxLFerAN7zFMIg1Df+TGuFvXoISniFTX7NW+QfIjLElDSHI5xjMygNDECHI1apUNgriJNKAfjU9bYtBMS0tpKmqMIFAAAcRhHQikVjCGKJtr+AhsBAmQz0wAm93jrhWVvXpR4nYED3smap2syB8DGDWaG0IqUnjbPeeh6QmHsP7I8BwcW2z7wxbgA+J8bTllnKs252zjEsOcac4ihTsdCuRPMMp6wOdOalopvhyZR7IaEeI2J8jQmQB1b7PZlrwA2vmnvJ17rFaUYBURtO2d2Rm0iCLcwWgzakDKBI2sv9lN5SA38-FMFyznYcEOTIADyMmn5niOcRIPEDq9vMMtOAoRrAuIHmcQBfiBOgBQ+Fz5UXvBD2shVHjnY2P1bKTMLjoReMnweyAwrfYGuibI4QLAiRZMka87cr4CBYeFJyC56zXZPPg567lgH+XEdFZLKhP4GhrDNhLZunFwHm5YzboUcr+3JTdGkmVrJqakaAmq+yPrCN2MiZI+JijtW+d2eR-AXnFNesi5LANppQ2n2gFDP5oYm38hoA4ORGVcq1gfNV3Y+tS2YxTZCzprIrkNvRBeFtb1awQt0iGCpQg03fzgA1RhYAA7CC2ZrlegALMaLJB3UguWW8T60AZfulzAO+D8grGGNBeIYDgLF1wmGd5YpV7jeHOw+PkNJ2QbmQ3vFgIPzOxJXtQi09gxB7wR1r1hml0NSA8fLLb1A1hrBfuw-CVM7s3yfi74S82ETPuZA+GQdvnfu85NTFH80xBF-d866AUj3ShiA1UJuaAZYP5YcEtIWgjumCULV-TZZ2RoBtJeP585eofbxSudcZlDAhBrHgBTLfO+Whsz6rH6w-4gEwEoEEaZYxAhy1QoBLQlE3eDesA4BtAGQKA6AtEOOcclOgGdcAeNOXuYG7ckGnIZe9o3Q4k3Ql6VMZQ-uD6rOEiH0fuHO5gwUi2OA9+LwueTAv4iW0sngpi2yse+yOAGQ36H+Y02ke+D4cuGQfu4MYAfY9SMhC6S6hKFkd+a4ti9gJo+khy+A2QNiXwKqeAcqiqQcpuHAv4X+ZYZM8q4g5m1IeI5AtsOgJuv4LeE+7e+yhKSkbCFmWwx+MK6aQgrS3+rQkhhA0h0ekMdWaioAI2Qw3aJu2Qs2PGSgC2S6V6mKdiv47urAxAZYMA2QMaAhTAq2jYGeiRT4yRHAm2AWT+heJodu9gDgrkjYGhauo8gEoggq9yTKFgvK-KdIu2E0dcF426IGLceBDOChpGbBdijqzqxMjYh+Jh2m76QgcApkbCSgqAgk8RYU64qAekguqUygScoAAA6sUK0CUVyhONIFOKyipOUXNpNBKOwEnnSBYHKptmIJQoDOuB5kMKGhLvYusAGPrmFBCXSNSDGhgAoYWtBn3LdsPGptPE9ugqhhCpFhpLhgvDzpDoLs1h1nRh4Tfv4CzCaCqjWldOIMQBGlCdGuyOUTGs1BVEgM2CWNYPCTBkifBiichuiS9hhtiVKHPLidEARgLk1hRkSVhrRBSR-GSRLPKeUeyUInkGzsMQwTEWAIylUcMZ3G1GFCrnOlBEwjOGwdNsYAgI0GsfAMci8L+GKewIJPiVKZiuLoJMSaYo2F8LKJnowDYu4E0HOoDHtDyhwOKM7NcrCREfuMQOcZcYZsZhSADLgDyiwPrhwKaXfOWCbmrn8FmPArQGoBtACCqoOLQKZCYVWP5iZKgLQDpjAHabaOwRpiYaUKtMQAoeaHWMHLACoQdIKWQAdLafaeoRNHYofiWegIOoflWVpq0sCcas2lflUfKNstZiSaAN3joPGbqZodkAwNYj8cyrlC0ISsKpSMkFfoSj1BnlGSBBptOWWcQKUDVFOaWYOicHPpwN6rQGzG5jKoYABYQoJIvrJsWZ+YQOgV2RET2WguZsodNpAq0JloQgId0RwE2ccn6PYe8T6Q4TuRwHsesM4ZubBeaLUp7FSGgOGb0U6v0YsSUAOMkcfjqkAfqsAIWrJvAJuMAPOieB+KgM2AACIADSrwuAmgiASSe4mgy4PA9AVY0gPA3Z5gjKt+auWQuhTA5+Juq2Qgr+v49mAhFyYUEkeIhM9meWBeGObmWO8mMWoU+mxl4ujoNlGILmGyvMvGx08wHgIgc6s6Gg2yv04uFCyikFM53u7iiFsAXh1uVR+U76LwsWiFDp9mxwd2YKmJ2W2poA248ZrwogHAGYdu2Ftoyeza+AhgHwSgj+02nhTqLwdhWYy5VVqWJg1mGRpk76du+GB8XSLpawm4Lpkp0OLp1UcmQuiMjBYA8R4sMxGhsGageeQqIqZhKJ+yW0q1BlkZdisGd2CGwCqJQWNQohnUf8POoA4FH0F4gMoRF4al5g8hERy5rZiI-Uo6T5UFph2yrp0O+y+W458qLwi2V6-Y0mpkJugMIl82ghDgYIIhnO+8ANQuYFi+d1nYrad1yAz1L1Vcb1HxnYbU8K48G+TASUmwbwGw0gzQRupQ8qfSAQS1HBJlsVD4ZygMWRBeGFTNrV5A-hgIzAHpN1mNwx4Ij1nY+NoAr1lF81E2fAHwhKLAPA0N7RNiVNyyWu3poAWt2y2RmEeR0ABR5AQNFBGJWcG4y5AMHmVR02LBygMZ8toAcZCWWGAhN+xgPprQ3Ngp+yZ19AgkKhKkZmKWvFJgZy1mChhVayWRA0RtLQ+RhRlt6sG4YUxl0Qx8944gVhHgoURQoA6AE+SZJmHNPhvt+eGICh-y+QOAIVrwtN9Naw158kTNGeZysehl9AHZYm42tAiQfAYdkN9AIVauwNGeeeXdCNwhQt+8vWYtpAwxjYj1agMtctc1oAD8Tw8UUUZNLgFN3K1YZpUUjp+GaNhJHpXp8RKAuiHgLwh+XgayLGNpL2XwG4Ge61niAWE4my-wReaagI4FQZoU1wH44K0Fgey9MtBNCugDnMJ65EAAbOQctukBQSgwFMaJyRNgiYdciaDqic9mhq9sKXPFuZ-CzD5KFuUQIvAx9Eg6MbTktPTvPog90Jg6vBQeg8tkg64W3gwB3kPj3t+dfChdfOdkvoSkJpvWvnTSGYEdvrvgvYfsflymfgmBfquV7aoQ-qUWwNct3W-vAMjVDBYT-loi+P-oAXqiAcEQgZAcETAYSnAQgUgRrqgUJqIritQeqbQXXEg1qdOogH8CwrXBkCMQ+QaW2QuTptmbzA6U6RLhfdKVfbKfsq2ePgIz3Wsn5PkOsBRZvXWK0JWOoE0GPT0cXeWM7ZvW7XWPsJvv8DhShQ6ZudYYlbtTUS0ifmgi8ERYU-lbHS9M2Unnbl-YKT6ZhW1CsSpkRYTGFdRomFyh+dFflZlQDFXTkFYb+AwqgsQP0uwiswCJwvXbAPgOqjxPZs1Gs+LvMPlnlcFLXfU4Fk04sZpkwALaDSaGoBoM8K-i0wqRM4TOIrYFFVjJlXgoCyQzED5MFOs0nps9cA87IeYHoH0S6o2NSLRSjqlBxSAdxT0nxXQnQnoBEIQDCM2PANkDCPuKgPEp2K+E9M+mcQAJx0KvgsCzX5ULUs0mijxyplVVFW5z0dxPKCQy7sYjXiuKZdai4Q5TUEn+QyvdYhJQMZBIMKEqSLUg2ZW4g6U+ZQuYkiv2ahEatwXmjdbBTvXdPiGZ4mGgpQmYmOH21x0TNvb7Jlh028wit0ZquEBmsu1yFytrOXIGPP66NrCNjCCdHj0YP8OT6CMFz9nTbFBrAivmOICmv41RF0qkpcIIo8TfDFCSp63JTLKkpGNbSAQmBxrwpjbJRAREBgx5v8o1TiAZSzjFh1SFTya5H2BqR5vKC+ycIEpErWAttVSUp0jQrBSVigkO5zod1rkcC0k4AEAkCMlIAxprEID0o6nFABZVVPGVEgptRq6-jdoet-C63rtcp-HQAAlzpAnZ42Lc2kDRBMlm0fyjalvU0tpbGOopH5b4UG0J25FJ0m0p2hZrtEAUBzK1rnKhCqAhUqlpgnrAAjktoHRgB4M8nHX+Jomp1ClYY4Yil4Z4njXo0ymwC0R5CMa8DEB-q7NMJQhywcYMd-ofjcaEpQgg6IYXyajmgpOcZ-pw1KAljWUccyC3SEIOVQg3p-qN0YiCfmAl5SfSCeyQB6iJ7yeMcyBKc5CCSx7B0F6Cf8CEjBDweMCIfKDIccC0NoecgYf92ZrYfbLcnRBwb4evz8lEdYkke4a2b0cKcyDMeNCscljschfSBcdA6wC8coniAqfCaNbQ4icyBiemMHwKtSnpfSCZeRddJ5cGfXCRcjXFcF4Sfi55d0J2ozg8fRclfZDJdqfReafafkC6eKcF5GefgmfKcBQWfyDBRQDrHIEAKG3geBqQeC3BRosMUYsxNMBkDVR5rbIdt81q4drWeQkPDnMxB7vVprfcCCnfAQdjb4o4gXAJ1yDbcTSefcCvA5AIBnFKpkCWAhWXedGyg3fyA1zG3ZBYBPfXAvdvcfccDnB4zxMNjHw8Ctjthdg9gxzUTrDHy3H3EzgCR0fcOczWpYBSgUzgJAwa7lKENY8wySfiDSInXk-Qz-biBHOKC09mOvOPkE96xE99jjfZ1YbM9OzVcSCx588U9Z0SA50yPhIkKc-mjc95zhUS-tYC-iARDy8KL0-5bC8iIS+KheNhI68BTkx3BWeDjgp+b6R9r5GHfG8Ylm8m8QpnfTeIoA-FhAA
[codesandbox]: https://codesandbox.io/s/typescript-playground-export-forked-vjsnfc?file=/index.ts

**Comment by mariuslundgard** [comment]
Looks like this proposal would make this possible:

```ts
import {q} from 'groqd'

const data = await client.fetch(
  q('*')
    .filter("_type == 'bookmark' && defined(url)")
    .slice(0, 1)
)
```

And get typed & validated results back.

I think this is a good enhancement of the client API.

It's still unclear to my why `{query: string, schema: {parse(data: unknown): TypedResponse}}` is better than the less verbose `{query: string, validate(data: unknown): TypedResponse}`. Maybe you can expand on this?

**Comment by mariuslundgard** [comment]
Would also be good to see an example which includes query params.

**Comment by stipsan** [comment]
@mariuslundgard 
> It's still unclear to my why `{query: string, schema: {parse(data: unknown): TypedResponse}}` is better than the less verbose `{query: string, validate(data: unknown): TypedResponse}`. Maybe you can expand on this?

For libraries like `groqd` where you write a typed query, then you indeed don't get a lot from the extra nesting as you don't have much reason to touch `schema` in your own code. You just want to pass it to `@sanity/client` and get types back, sure.

It's when you put it in context with typegen libraries that rely on inference (like `groqz`) that it starts to make sense having an object with a `parse` method. Where you instead write an arbitrary query, and types are inferred from it as a best-effort. Sometimes the typegen faces something too dynamic and it de-opts resulting in a wider type than what you might want.

For example, you query:
```groq
*[_type=='movie']{..., "popularity": select(
  popularity > 20 => "high",
  popularity > 10 => "medium",
  popularity <= 10 => "low"
)}
```
And while in groqd you would [write this query](https://github.com/FormidableLabs/groqd#conditional-selections-with-grab) in a way that lets TS know that `popularity: 'high' | 'medium' | 'low'`. It's possible for groqz to be able to do that too, by combining studio schema information, parsing your query, and doing an introspection evaluation. But Rome weren't built in a day so there'll be a lot of cases like these where libraries like groqz won't be able to narrow things down and the best it can do is give you `string`, or in worst scenario:  `unknown`.

In any case, then it's nice to have easy access to the schema so you can narrow down the typings on your own:
```ts
import {groq} from 'groqz'

const typedQuery = groq`*[_type=='movie']{..., "popularity": select(
  popularity > 20 => "high",
  popularity > 10 => "medium",
  popularity <= 10 => "low"
)}`
const narrowerSchema = typedQuery.schema.extend({popularity: z.enum([z.literal('high'), z.literal('medium'), z.literal('low')])})
const data = await client.fetch({...typedQuery, schema: narrowerSchema})
```

Look at the bottom of the playground to see a couple of more scenarios that makes use of the easy schema access to do other things that Zod codebases often do.

**Comment by saiichihashimoto** [comment]
‘groqd’ & ‘groqz’ look phenomenal and exactly the kind of help groq needs. The thing I’m seeing is they’re both schema unaware (for good reason around the flexibility of the content lake). My initial thinking of an approach would be a builder that was context _aware_, ie the builder would only provide and allow methods & params that adhere to the schema. I think they’re both valid and honestly very similar approaches. The main reason I’m seeing that is to continue having one source of truth. The context unaware approaches end up having you use a zod-like approach to validate output, but that ends up mirroring your sanity schemas again.

**Comment by stipsan** [comment]
@saiichihashimoto we're exploring that aspect of type safety as well and will share our findings once we have a solution or a plan  😌  And `groqz` will be schema-aware as whatever strategy is used to provide type-safety it's hard to imagine one that doesn't take your Studio Schema into account. If you don't have a single source of truth then is it really runtime safe?  🤔

**Comment by gksander** [comment]
👋 [`groqd`](https://github.com/FormidableLabs/groqd/) author here. I love to see this conversation happening!

I think what you have proposed here looks good. It seems like this would work out of the box with `groqd`, but also allow non-groqd users to provide their own simple, lightweight solutions if they'd like (e.g. they could plug into something like `yup` or other schema validation libraries, or roll their own).

Is the idea to _also_ provide legacy support for just providing a groq string to `client.fetch`, and just overload the function?

**Comment by stipsan** [comment]
> Is the idea to _also_ provide legacy support for just providing a groq string to `client.fetch`, and just overload the function? 

Yes, if given a string it works just like before. 👍

**Comment by wimbarelds** [comment]
I like the part of the implementation that Sanity client takes care of (though I'd love for Sanity to take care of more). But assuming that Sanity opts to stay out of providing a type-providing implementation...

It feels like an ideal (third or first party) solution would be:

1. wrap defineType, defineField, defineArrayMember
2. in those functions, return sanity-schema-types _and_ a typesafe query-builder
3. query builder then provides query and schema for client.fetch, thus providing appropriate returntypes
4. optionally also provides appropriate zod definitions for validation

However, if something like this were made (first or third party); that seems like it could still be compatible with the implementation outlined in this issue.

**Comment by wimbarelds** [comment]
Have there been any updates in this area?

**Comment by JohnGemstone** [comment]
> Have there been any updates in this area?

I would look into https://github.com/FormidableLabs/groqd/
It's a GROQ query builder that also outputs matching zod schemas you can use to validate your data and type your codebase.

**Comment by stipsan** [comment]
> Have there been any updates in this area?

Still in the exploratory phase. We remain convinced that typed GROQ brings a lot of value and committed to deliver this. It's still too early for us to be able to share any timelines as it's still undetermined what tooling and features we want to ship.
There's a lot of interesting ideas bouncing around internally that we discuss on a weekly basis. And the concern is "can it really be done this way or is it too ambitious" and a lot of other unknowns.

For me, for example, the dream setup would be to continue to write GROQ template strings. And have my IDE tell me if there's a typo in my query. Or if I'm asking for a field that doesn't exist. Or asking for an array when it's actually a string. Types for my app should be generated without me having to change my workflow in any way, I edit the query and save the file and it updates. I edit my Studio schema, it should update the typings. If I remove a field my IDE should tell me right away if it'l break my app. If I change the type of a field it should offer to refactor my code to match the change.

It's still too early to tell if what I'm describing above is even possible, or if we'll have to make some compromises.
I hope this sheds some light as to why we're a bit quiet on this while we're deep down the rabbit holes 🙂

**Comment by logemann** [comment]
@stipsan event though its quite here these days... i like your summary of your "dream" workflow. Your mentioned approach would be pretty awesome.

**Comment by stipsan** [comment]
In case you missed the announcement on the new TypeGen feature: https://www.sanity.io/blog/introducing-sanity-typegen

Since this issue started our ecosystem has evolved. There no longer is a `client.fetch`call for all your GROQ. If you're using [Sanity Presentation](https://www.sanity.io/docs/loaders-and-overlays) you're probably calling `loadQuery` and `useQuery` instead.
In light of this it doesn't make sense to enforce runtime checks (like with `zod`) in `@sanity/client`'s API. 

Thanks for the discourse here and feel free to continue the discussion on [the #typescript channel on our Slack](https://slack.sanity.io/)
