### ISSUE TITLE
Microsoft Edge “Object doesn’t support this action”

### ISSUE THREAD

**Issue by danielmahal** [sanity-io/client#9]
Version: Microsoft Edge 25.10586.672.0

Getting a javascript exception in Edge. Related to EventSource?

Attaching screenshots of console and breakpoint:

![pasted_image_at_2016_12_01_01_40_pm](https://cloud.githubusercontent.com/assets/415411/20795028/71053026-b7cf-11e6-94c6-4d94b37274e3.png)

![pasted_image_at_2016_12_01_02_03_pm](https://cloud.githubusercontent.com/assets/415411/20795037/781ed5b0-b7cf-11e6-9e28-16777c94501a.png)

**Comment by rexxars** [comment]
Thanks for reporting, looking into it now

**Comment by rexxars** [comment]
Found the issue and pushed a new version, however, we've discovered a bug in the API that is preventing the polyfill in IE/Edge from working. It will hopefully be fixed later today - for now I'll leave this open.

**Comment by rexxars** [comment]
Bug should be fixed now, let us know if you are still having issues.
