### ISSUE TITLE
Uploading an image with a filename specified always results in the last character of the filename being removed in the browser.  

### ISSUE THREAD

**Issue by abusch419** [sanity-io/client#98]
**Describe the bug**

Trying to upload an image asset with a filename specified always results in the last character of the filename being removed in the browser.  

**To Reproduce**

Upload an image using `Sanity.client.upload()`

```
const fileUpload = await client.assets.upload('image', pngBuffer, {
  contentType: 'image/png',
  filename: 'myFile',
})

console.log('The file was uploaded!', fileUpload)
```

**Expected behavior**

I expect to see the filename 'myFile' in the browser under the media details, but I see 'myFil'.
Oddly enough in the media collection view I do see the correct filename.
I also see the correct filename in the request under the `originalFilename` key. 
Please see screenshots.

**Screenshots**
Filename with last character removed
<img width="862" alt="Screen Shot 2023-02-01 at 1 00 46 PM" src="https://user-images.githubusercontent.com/48231024/216125233-c1d2703f-2c09-49a1-bc24-8698f6ea1a41.png">

Filename showing as specified 
<img width="953" alt="Screen Shot 2023-02-01 at 1 03 54 PM" src="https://user-images.githubusercontent.com/48231024/216125893-492c02c9-8664-41ac-81a5-1499976e3f2d.png">

Correct name in the request under the originalFile key
<img width="758" alt="Screen Shot 2023-02-01 at 1 06 17 PM" src="https://user-images.githubusercontent.com/48231024/216126331-1c2c0c47-a1e3-47ae-a1a4-ccdc0662e6bb.png">

**Which versions of Sanity are you using?**

"@sanity/client": "^3.4.1"

**What operating system are you using?**

Mac OS Monterey 12.1

**Which versions of Node.js / npm are you running?**

8.19.3
v16.19.0

**Comment by rexxars** [comment]
This seems to be a problem in the media browser, not the actual upload. I've raised a PR to address it here: https://github.com/sanity-io/sanity-plugin-media/pull/120
